# Downloads
# podman pull --arch=amd64  python:3.12-slim && podman tag docker.io/library/python:3.12-slim  localhost/python:amd64-3.12-slim
# podman pull --arch=arm64  python:3.12-slim && podman tag docker.io/library/python:3.12-slim  localhost/python:arm64-3.12-slim

# Build command:
# podman build --platform linux/arm64 --build-arg BASE_TAG=arm64-3.12-slim -t engine:arm64-v5 -f Dockerfile.engine .
# podman build --platform linux/amd64 --build-arg BASE_TAG=amd64-3.12-slim -t engine:amd64-v5 -f Dockerfile.engine .

ARG BASE_TAG=

FROM localhost/python:${BASE_TAG}
# FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY ./fsm_agent ./fsm_agent
# COPY ./api ./api
COPY ./ml ./ml
# COPY ./resources ./resources
# COPY ./__init__.py ./__init__.py
COPY ./.env ./.env
# COPY ./.python-version ./.python-version
# COPY ./pyproject.toml ./pyproject.toml
# COPY ./uv.lock ./uv.lock
# COPY ./agents ./agents
COPY ./rag/rag_with_ollama.py ./rag/rag_with_ollama.py
# COPY ./rag/chroma_capstone_db_new_small ./rag/chroma_capstone_db_new_small

EXPOSE 8080

CMD ["python", "./fsm_agent/run_fsm_server.py", "--host", "0.0.0.0", "--port", "8080"]
