FROM python:latest
# FROM ollama/ollama:latest

# Set working directory
WORKDIR /app

# Install Ollama CLI dependencies
# RUN apt-get update && apt-get install -y curl unzip

# Install Ollama CLI
# RUN curl -sSL https://ollama.com/install.sh | bash

COPY requirements.txt /app/requirements.txt
COPY test_chromadb.py /app/
COPY .env /app/

RUN pip install -r requirements.txt


CMD ["uvicorn", "test_chromadb:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

# RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Copy an entrypoint script
# COPY entrypoint.sh /app/entrypoint.sh
# RUN chmod +x /app/entrypoint.sh

# CMD ["/app/entrypoint.sh"]

# RUN ollama pull llama-3.1-8b

# CMD ["python", "test_chromadb.py"]
